const list = (value) => Array.isArray(value) ? value.filter(Boolean) : String(value || "").split(/[,;\n]/).map((item) => item.trim()).filter(Boolean);
const ref = (type, id) => ({ reference: `${type}/${id}` });
const textCode = (text) => ({ text: String(text) });
const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);

export function buildClinicianFhirBundle(archive = {}) {
  const profile = archive.wellness?.profile || {};
  const subject = ref("Patient", "subscriber");
  const resources = [{ resourceType: "Patient", id: "subscriber", identifier: [{ system: "https://natures-elixirz-os.web.app/subscriber", value: String(archive.account?.uid || "unknown") }], name: profile.name ? [{ text: profile.name }] : undefined }];
  const observation = (id, loinc, display, value, unit, code) => ({ resourceType: "Observation", id, status: "final", category: [{ coding: [{ system: "http://terminology.hl7.org/CodeSystem/observation-category", code: "vital-signs" }] }], code: { coding: [{ system: "http://loinc.org", code: loinc, display }] }, subject, valueQuantity: { value: Number(value), unit, system: "http://unitsofmeasure.org", code }, note: [{ text: "Self-reported in Nature's Elixirz OS." }] });
  if (profile.height) resources.push(observation("height", "8302-2", "Body height", profile.height, "in", "[in_i]"));
  if (profile.weight) resources.push(observation("weight", "29463-7", "Body weight", profile.weight, "lb", "[lb_av]"));
  list(profile.conditions).concat(list(profile.otherHealthConditions)).forEach((value, index) => resources.push({ resourceType: "Condition", id: `condition-${index + 1}`, clinicalStatus: { coding: [{ system: "http://terminology.hl7.org/CodeSystem/condition-clinical", code: "active" }] }, verificationStatus: { coding: [{ system: "http://terminology.hl7.org/CodeSystem/condition-ver-status", code: "unconfirmed" }] }, code: textCode(value), subject, note: [{ text: "Subscriber-entered; not diagnosed or verified by Nature's Elixirz." }] }));
  list(profile.medications).forEach((value, index) => resources.push({ resourceType: "MedicationStatement", id: `medication-${index + 1}`, status: "active", medicationCodeableConcept: textCode(value), subject, note: [{ text: "Subscriber-entered medication text; reconciliation required." }] }));
  list(profile.allergies).forEach((value, index) => resources.push({ resourceType: "AllergyIntolerance", id: `allergy-${index + 1}`, patient: subject, verificationStatus: { coding: [{ system: "http://terminology.hl7.org/CodeSystem/allergyintolerance-verification", code: "unconfirmed" }] }, code: textCode(value), note: [{ text: "Subscriber-entered allergy or intolerance; clinical verification required." }] }));
  list(profile.healthGoals).forEach((value, index) => resources.push({ resourceType: "Goal", id: `goal-${index + 1}`, lifecycleStatus: "active", description: textCode(value), subject, note: [{ text: "Subscriber-selected wellness intention, not a prescribed clinical goal." }] }));
  resources.push({ resourceType: "QuestionnaireResponse", id: "wellness-history", status: "completed", subject, authored: archive.exportedAt, item: [
    ["dietary-pattern", "Self-reported dietary pattern", profile.dietaryPattern], ["activity", "Self-reported activity rhythm", profile.activity], ["surgical-history", "Self-reported surgical history", profile.surgicalHistory], ["avoid-ingredients", "Ingredients avoided", profile.avoidIngredients],
    ["kernel-history", "Nature's Elixirz wellness activity and observations", JSON.stringify({ journey: archive.wellness?.journey || {}, movement: archive.wellness?.movement || {}, feedback: archive.wellness?.exchange?.feedback || {}, recipes: archive.recipes || [], smoothieAiHistory: archive.smoothieAiHistory || [], mealPlanAiHistory: archive.mealPlanAiHistory || [] })],
  ].map(([linkId, text, value]) => ({ linkId, text, answer: [{ valueString: value || "Not provided" }] })), extension: [{ url: "https://natures-elixirz-os.web.app/fhir/StructureDefinition/data-boundary", valueString: "Patient-generated wellness data. Not independently verified, diagnostic, or clinician-authored." }] });
  return { resourceType: "Bundle", id: `natures-elixirz-${Date.now()}`, type: "collection", timestamp: new Date().toISOString(), entry: resources.map((resource) => ({ fullUrl: `urn:uuid:${resource.resourceType.toLowerCase()}-${resource.id}`, resource })) };
}

export function buildClinicianSummary(archive = {}) {
  const profile = archive.wellness?.profile || {};
  const section = (title, value) => `<section><h2>${escapeHtml(title)}</h2><pre>${escapeHtml(typeof value === "string" ? value || "Not provided" : JSON.stringify(value || {}, null, 2))}</pre></section>`;
  return `<!doctype html><html><head><meta charset="utf-8"><title>Nature's Elixirz clinician handoff</title><style>body{font:14px/1.5 Arial,sans-serif;max-width:900px;margin:35px auto;padding:0 22px;color:#15232b}h1{color:#075e54}h2{border-bottom:1px solid #ccd8dc;padding-bottom:5px}aside{background:#fff4d6;border:1px solid #e0b34a;padding:14px}pre{white-space:pre-wrap;font:13px/1.5 Arial,sans-serif}.meta{color:#52646c}</style></head><body><h1>Subscriber wellness handoff</h1><p class="meta">Prepared ${escapeHtml(new Date().toLocaleString())} by the subscriber through Nature's Elixirz OS.</p><aside><strong>Clinical boundary:</strong> Patient-generated wellness information. Nature's Elixirz is not a healthcare provider; entries and calculated observations are not independently verified, diagnostic, or treatment recommendations. Reconcile medications/allergies and verify all information with the patient.</aside>${section("Patient-entered profile", { name: profile.name, age: profile.age, heightIn: profile.height, weightLb: profile.weight, dietaryPattern: profile.dietaryPattern, activityRhythm: profile.activity })}${section("Conditions and surgical history", { selectedConditions: profile.conditions, otherConditions: profile.otherHealthConditions, surgicalHistory: profile.surgicalHistory })}${section("Medication and allergy reconciliation", { medications: profile.medications, allergiesOrIntolerances: profile.allergies, avoidedIngredients: profile.avoidIngredients })}${section("Patient wellness goals", profile.healthGoals)}${section("Nutrition formulas and plans", { savedRecipes: archive.recipes, smoothieGenerationHistory: archive.smoothieAiHistory, mealPlanGenerationHistory: archive.mealPlanAiHistory })}${section("Wellness activity and movement observations", { journey: archive.wellness?.journey, movement: archive.wellness?.movement })}${section("Subscriber experience feedback", archive.wellness?.exchange?.feedback)}<p class="meta">Administrative, billing, email-delivery, household-link, and private chat records are excluded.</p></body></html>`;
}

function download(content, type, filename) { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }
export function downloadClinicianPackage(archive, uid) { const stem = `natures-elixirz-clinician-handoff-${String(uid).slice(0, 8)}-${new Date().toISOString().slice(0, 10)}`; download(buildClinicianSummary(archive), "text/html", `${stem}.html`); download(JSON.stringify(buildClinicianFhirBundle(archive), null, 2), "application/fhir+json", `${stem}-fhir-r4.json`); }
